CREATE DATABASE IF NOT EXISTS `cs370_section02_csquids` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
USE `cs370_section02_csquids`;

CREATE TABLE users (
    userID BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    email VARCHAR(250) UNIQUE NOT NULL,
    password VARCHAR(250) NOT NULL,
    firstName VARCHAR(50),
    lastName VARCHAR(50)
);

CREATE TABLE auction_items (
    auction_itemID BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    sellerID BIGINT UNSIGNED NOT NULL,
    title VARCHAR(100) NOT NULL,
    description VARCHAR(512),
    startPrice BIGINT UNSIGNED NOT NULL,
    startDate DATETIME NOT NULL,
    endDate DATETIME NOT NULL,
    FOREIGN KEY (sellerID) REFERENCES users(userID)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);

CREATE TABLE bids (
    bidID BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    bidderID BIGINT UNSIGNED NOT NULL,
    itemID BIGINT UNSIGNED NOT NULL,
    offer_price BIGINT UNSIGNED NOT NULL,
    time DATETIME NOT NULL,
    FOREIGN KEY (bidderID) REFERENCES users(userID)
        ON DELETE CASCADE
        ON UPDATE CASCADE,
    FOREIGN KEY (itemID) REFERENCES auction_items(auction_ItemID)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);
